###########################################################
# $Author: bucknerk $ 
# $Id: Makefile,v 1.11 2008/04/29 19:24:02 bucknerk Exp $
# $Log: Makefile,v $
# Revision 1.11  2008/04/29 19:24:02  bucknerk
# Fixed these so that they would compile/install nicely on new machine. I think
# that they should work now.
#
# Revision 1.10  2007/07/13 19:48:19  bucknerk
# I think it is really ready to rock and roll now.  Have to check the dev
# version I just installed but everything seems fine.
#
# Revision 1.9  2007/07/13 19:04:12  bucknerk
# Completely restructured this.  Have not yet removed all the junk from it but am
# working on it.  This now relies on Makefiles in the subdirectories.
#
#
# 
# Makefile for BigBangOnline (BBO).  The directory and some files may be named
# bbn but that is a legacy thing. This is file is
# 
# This file was modified from the original to simplify and standardize the make
# process.  All paths will be relative to the working directory (the one in
# which this makefile resides) or specific to the installation i.e. /var/www.
# 
# Makefile for suite


# this is the data password. I dislike placing it in any file but this is the 
# least offensive place
DB_PW=jGFcfj&%^4678hfc

# source variables
# WAY too much stuff here.  Need to winnow it out.
ROOT=$(strip $(shell pwd))
SRC_DIR=$(ROOT)/src
BIN_DIR=$(ROOT)/bin

# destination variables
INSTALL_DIR=/home/www
INSTALL_GROUP=apache

SUF=$(findstring dev,$(MAKECMDGOALS))
# change this to prevent an old version of make from an error. This causes all
# variables set here to be exported to sub-makes. The better way according to
# the gnu manual is
.EXPORT_ALL_VARIABLES:


# Main targets
# this is an odd and not guaranteed but probably support special target.  It is
# similar to the .SUFFIXES: rule.  This one tells make that the list are all
# target names for which files will NEVER exist. It keeps make from searching
# for those files 
.PHONY: clean bbn bbndev installbbn installdev

# This is really dumb and does not seem to make any sense as this is the
# top-level makefile
first:
	@echo "USAGE: make [bbn|bbndev|installbbn|installdev|clean]"
	@echo "Install options should be run as root (or sudo) to ensure"
	@echo "permissions are correct."



# This was a test to see about compiling f77 code with the new gfortran
# (f95/2003) compiler.  As you can see it is not always straight forward.  
#	gfortran -std=legacy -o src/bbnsim/bbnsim -O3 src/bbnsim/*.f
#	gfortran -std=legacy -ffixed-line-length-none -o src/constraint/constraint -O3 src/constraint/cosmology6.f
# Dependency targets

bbn bbndev: $(BIN_DIR)
	@echo "MAKING $@"
	@cd src && $(MAKE) $@
	@echo "FINISHED MAKING $@"

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

# this is something that relies in the directories actually existing. If make is
# doing the install it can assume that the 'from' directories exist because the
# product was just made. As for the destination cp -R will generally create
# them.  If this is problem, use mv instead (besides which, its really faster).
# Probably should use the install/ginstall program instead and run as root. Need
# to check this out.

installbbn: $(INSTALL_DIR)  $(INSTALL_DIR)/bbn $(INSTALL_DIR)/bbn/bin \
	$(INSTALL_DIR)/bbn/src $(INSTALL_DIR)/bbn/tmp
	cd $(SRC_DIR) && install -m 664 -g $(INSTALL_GROUP) cgi_specs.html cgi_specs.css $(INSTALL_DIR)/html
# copy html files
	cd $(BIN_DIR) && install -m 775 -g $(INSTALL_GROUP) constraint bbnsim run_bbnsim $(INSTALL_DIR)/bbn/bin
# copy 'normal' binaries 
	cd $(BIN_DIR) && install -m 775 -g $(INSTALL_GROUP) bbn $(INSTALL_DIR)/cgi-bin
# copy cgi script
	cd $(SRC_DIR) && install -m 664 -g $(INSTALL_GROUP) *.pm approve_registration.pl $(INSTALL_DIR)/bbn/src
# copy perl modules

# For the development version we won't change the html file, but we still install 
# executables and modules.
installdev:  $(INSTALL_DIR)  $(INSTALL_DIR)/bbndev $(INSTALL_DIR)/bbndev/bin \
	$(INSTALL_DIR)/bbndev/src $(INSTALL_DIR)/bbndev/tmp
	cd $(BIN_DIR) && install -m 775 -g $(INSTALL_GROUP) constraint bbnsim run_bbnsim $(INSTALL_DIR)/bbndev/bin
# copy 'normal' binaries 
	cd $(BIN_DIR) && install -m 775 -g $(INSTALL_GROUP) bbndev $(INSTALL_DIR)/cgi-bin
# copy cgi script
	cd $(SRC_DIR) && install -m 664 -g $(INSTALL_GROUP) *.pm approve_registration.pl $(INSTALL_DIR)/bbndev/src
# copy perl modules

# clean removes generated by compilation/make
clean:
	cd src && $(MAKE) clean
	/bin/rm -f install uninstall
	/bin/rm -rf $(BIN_DIR)


$(INSTALL_DIR):
	mkdir -m 2775 $(INSTALL_DIR)
	chown root:apache $(INSTALL_DIR)
$(INSTALL_DIR)/bbn$(SUF):
	mkdir -m 2775 $(INSTALL_DIR)/bbn$(SUF)
	chown root:apache $(INSTALL_DIR)/bbn$(SUF)
$(INSTALL_DIR)/bbn$(SUF)/bin:
	mkdir -m 2775 $(INSTALL_DIR)/bbn$(SUF)/bin
	chown root:apache $(INSTALL_DIR)/bbn$(SUF)/bin
$(INSTALL_DIR)/bbn$(SUF)/src:
	mkdir -m 2775 $(INSTALL_DIR)/bbn$(SUF)/src
	chown root:apache $(INSTALL_DIR)/bbn$(SUF)/src
$(INSTALL_DIR)/bbn$(SUF)/tmp:
	mkdir -m 2775 $(INSTALL_DIR)/bbn$(SUF)/tmp
	chown root:apache $(INSTALL_DIR)/bbn$(SUF)/src
