#!/usr/bin/perl 
    # Main script for bbn suite
    # $Author: bucknerk $
    # $Id: ag_main.pl,v 1.36 2008/04/29 19:24:02 bucknerk Exp $
    # $Log: ag_main.pl,v $
    # Revision 1.36  2008/04/29 19:24:02  bucknerk
    # Fixed these so that they would compile/install nicely on new machine. I think
    # that they should work now.
    #
    # Revision 1.35  2007/07/30 17:13:45  bucknerk
    # changed the way the "use lib" pragma gets the name of the executable.
    #
    # Revision 1.34  2007/07/13 19:49:33  bucknerk
    # Fixed this to use the command name to choose the module path.
    # Hopefully this is not a buggy option.  Must finish checking the
    # dev version in operation.
    #
    #
    # CGI specifications for interfacing with bigbangonline.org server
    #
    # This file is NO LONGER AUTOGENERATED.  JUST FIX IT!
    #
    # GOING to add a couple of statements here that will determine where
    # this script looks for it module files. As we are calling these executables
    # bbn and bbndev and the module directories are /var/www/bbn/src and 
    # /var/www/bbndev/src respectively, all we have to do is tweak a variable
    # name to strip any leading information and use it to add a path name to the 
    # @INC array.  This is the same thing that the -I command line switch does.
    # The big important thing here is that the "use lib" statment is evaluated 
    # BEFORE any "code" statements, so the substitution has to be part of the 
    # statment itself.  Can't use $0 =~ s/^.*\/// before it for this reason and
    # if we put it in place of the split call, unlike C, the left-hand side is not
    # the result of the expression, it is the number of substitutions (1 in this
    # case) which is not the result we are looking for.

    #use lib "/var/www/",(split(/^.*\//,$0))[0],"/src ";
    #print @INC;
    use lib join("","../",split(/^.*\//,$0),"/src");

    # and that should fix everything.
    use warnings;
    use strict;
    use DBI;
    use ag_error;
    use ag_cgi;
    use ag_db;
    use agm_Administration;
    use agm_BBN_Simulator;
    use agm_BBN_Visualizer;
    use agm_BBN_Observations;
    use agm_Constraint_Generator;
    use agm_Rate_Library;
    use agm_Rate_Uncertainties;
    #use Data::Dumper;

    $ag_db::dbh = DBI->connect("dbi:mysql:$ag_db::username",
				$ag_db::username, $ag_db::pw,
				{ PrintError => 0, AutoCommit => 0 }) 
	or report_error('BUG','DBI->connect failed',$DBI::errstr);

    # get CGI data from webserver, which comes from java application
    # returns a reference to a hash with at least the following properties
    #   HEADER, ID, USER, PW, ACTION
    my $in = read_cgi();
    
    #print Dumper($in);
    #log_cgi_request($in);

    $_ = authencate_user($in);
    report_error('INVALID_USER', $_) if ($_);

    if ($in->{ACTION} ne 'GET ID') {
	$_ = check_session_id($in);
	report_error('INVALID_SESSION', $_) if ($_);
    }

    report_error('BAD_HEADER',"HEADER=$in->{HEADER}") if ($in->{HEADER} ne '0.1' and $in->{HEADER} ne '1');

    my $action = $in -> {ACTION};
    if (not $action) {	report_error('BUG','Empty ACTION in main'); }
    elsif ($action eq 'GET RATE LIBRARY INFO') { agp_GET_RATE_LIBRARY_INFO($in); }
    elsif ($action eq 'GET OBS LIST') { agp_GET_OBS_LIST($in); }
    elsif ($action eq 'LOCATE RATES') { agp_LOCATE_RATES($in); }
    elsif ($action eq 'MODIFY RATE') { agp_MODIFY_RATE($in); }
    elsif ($action eq 'ERASE CONSTRAINT') { agp_ERASE_CONSTRAINT($in); }
    elsif ($action eq 'GET ID') { agp_GET_ID($in); }
    elsif ($action eq 'GET RATE INFO') { agp_GET_RATE_INFO($in); }
    elsif ($action eq 'BBN SIM SETUP') { agp_BBN_SIM_SETUP($in); }
    elsif ($action eq 'GET CONSTRAINT LIST') { agp_GET_CONSTRAINT_LIST($in); }
    elsif ($action eq 'ERASE OBS') { agp_ERASE_OBS($in); }
    elsif ($action eq 'GET BBN RUN LIST') { agp_GET_BBN_RUN_LIST($in); }
    elsif ($action eq 'BBN RUN EXIST') { agp_BBN_RUN_EXIST($in); }
    elsif ($action eq 'BBN SIM UPDATE') { agp_BBN_SIM_UPDATE($in); }
    elsif ($action eq 'GET RATE UNCERTAINTY DATA') { agp_GET_RATE_UNCERTAINTY_DATA($in); }
    elsif ($action eq 'GET OBS DATA') { agp_GET_OBS_DATA($in); }
    elsif ($action eq 'COPY RATE UNCERTAINTIES TO SHARED') { agp_COPY_RATE_UNCERTAINTIES_TO_SHARED($in); }
    elsif ($action eq 'ABORT BBN SIM') { agp_ABORT_BBN_SIM($in); }
    elsif ($action eq 'SAVE CONSTRAINT') { agp_SAVE_CONSTRAINT($in); }
    elsif ($action eq 'GET RATE UNCERTAINTIES') { agp_GET_RATE_UNCERTAINTIES($in); }
    elsif ($action eq 'ERASE RATE UNCERTAINTIES') { agp_ERASE_RATE_UNCERTAINTIES($in); }
    elsif ($action eq 'SAVE OBS') { agp_SAVE_OBS($in); }
    elsif ($action eq 'GET BBN RUN INFO') { agp_GET_BBN_RUN_INFO($in); }
    elsif ($action eq 'LOGOUT') { agp_LOGOUT($in); }
    elsif ($action eq 'GET RATE LIST') { agp_GET_RATE_LIST($in); }
    elsif ($action eq 'ERASE BBN RUN') { agp_ERASE_BBN_RUN($in); }
    elsif ($action eq 'GET BBN SIM TYPES') { agp_GET_BBN_SIM_TYPES($in); }
    elsif ($action eq 'SAVE RATE UNCERTAINTIES') { agp_SAVE_RATE_UNCERTAINTIES($in); }
    elsif ($action eq 'ERASE LIBRARY') { agp_ERASE_LIBRARY($in); }
    elsif ($action eq 'GET OBS INFO') { agp_GET_OBS_INFO($in); }
    elsif ($action eq 'SAVE BBN SIM') { agp_SAVE_BBN_SIM($in); }
    elsif ($action eq 'GET BBN LOOPING DEFAULTS') { agp_GET_BBN_LOOPING_DEFAULTS($in); }
    elsif ($action eq 'GET CONSTRAINT INFO') { agp_GET_CONSTRAINT_INFO($in); }
    elsif ($action eq 'OBS EXIST') { agp_OBS_EXIST($in); }
    elsif ($action eq 'GET RATE LIBRARY LIST') { agp_GET_RATE_LIBRARY_LIST($in); }
    elsif ($action eq 'GET TIMEOUT') { agp_GET_TIMEOUT($in); }
    elsif ($action eq 'COPY OBS TO SHARED') { agp_COPY_OBS_TO_SHARED($in); }
    elsif ($action eq 'COPY BBN RUN TO SHARED') { agp_COPY_BBN_RUN_TO_SHARED($in); }
    elsif ($action eq 'RUN BBN SIM') { agp_RUN_BBN_SIM($in); }
    elsif ($action eq 'REGISTER') { agp_REGISTER($in); }
    elsif ($action eq 'COPY CONSTRAINT TO SHARED') { agp_COPY_CONSTRAINT_TO_SHARED($in); }
    elsif ($action eq 'GET RATE LIBRARY ISOTOPES') { agp_GET_RATE_LIBRARY_ISOTOPES($in); }
    elsif ($action eq 'MERGE RATE LIBRARIES') { agp_MERGE_RATE_LIBRARIES($in); }
    elsif ($action eq 'GET CONSTRAINT DATA') { agp_GET_CONSTRAINT_DATA($in); }
    elsif ($action eq 'RUN CONSTRAINT GENERATOR') { agp_RUN_CONSTRAINT_GENERATOR($in); }
    elsif ($action eq 'COPY LIBRARY TO SHARED') { agp_COPY_LIBRARY_TO_SHARED($in); }
    elsif ($action eq 'GET BBN RUN DATA') { agp_GET_BBN_RUN_DATA($in); }
    else { report_error('BUG',"Unknown CGI property: ACTION=$action"); }

    $ag_db::dbh->disconnect();
