CREATE DATABASE bbndev;

GRANT ALL PRIVILEGES ON bbndev.* TO 'bbndev'@'localhost' IDENTIFIED BY
'jGFcfj&%^4678hfcd';

##### LOGS #####
CREATE TABLE logs_error (
Time DATETIME NOT NULL,
Session CHAR(20) NOT NULL,
Rnd SMALLINT UNSIGNED NOT NULL,
TimeOfError DATETIME NOT NULL,
Depth TINYINT UNSIGNED NOT NULL,
Dmsg CHAR(100) NOT NULL,
INDEX id (Time,Session,Rnd));

CREATE TABLE logs_error_full (
Time DATETIME NOT NULL,
Session CHAR(20) NOT NULL,
Rnd SMALLINT UNSIGNED NOT NULL,
Depth TINYINT UNSIGNED NOT NULL,
file TINYTEXT NOT NULL,
line INT NOT NULL,
type INT NOT NULL,
val INT NOT NULL,
cvsid TINYTEXT NOT NULL,
msg TINYTEXT NOT NULL,
dmsg TINYTEXT NOT NULL,
str MEDIUMTEXT NOT NULL,
datecompiled DATETIME NOT NULL,
INDEX id (Time,Session,Rnd));

CREATE TABLE logs_access (
Time DATETIME NOT NULL,
Session CHAR(20) NOT NULL,
Rnd SMALLINT UNSIGNED NOT NULL,
Username CHAR(20) NOT NULL,
IP CHAR(15) NOT NULL,
Depth TINYINT UNSIGNED NOT NULL,
INDEX id (Time,Session,Rnd));

CREATE TABLE logs_access_stack (
Time DATETIME NOT NULL,
Session CHAR(20) NOT NULL,
Rnd SMALLINT UNSIGNED NOT NULL,
Depth TINYINT UNSIGNED NOT NULL,
Request TINYTEXT NOT NULL,
INDEX id (Time,Session,Rnd));

CREATE TABLE logs_access_body (
Time DATETIME NOT NULL,
Session CHAR(20) NOT NULL,
Rnd SMALLINT UNSIGNED NOT NULL,
Body LONGTEXT NOT NULL,
INDEX id (Time,Session,Rnd));


##### ADMINISTRATION #####
CREATE TABLE sessions (
Session CHAR(20) NOT NULL, UNIQUE INDEX (Session),
Username CHAR(20) NOT NULL,
Password CHAR(64) NOT NULL,
IP CHAR(15) NOT NULL,
Permissions INT UNSIGNED NOT NULL DEFAULT 0,
Status SMALLINT UNSIGNED NOT NULL DEFAULT 0,
LastRequest DATETIME NOT NULL);

CREATE TABLE accounts (
Username CHAR(20) NOT NULL PRIMARY KEY UNIQUE,
Alias CHAR(40) NOT NULL,
Password CHAR(64) NOT NULL UNIQUE,
Email CHAR(80) NOT NULL,
CreateDate DATE NOT NULL,
PwChangeDate DATE NOT NULL,
MaxLogins SMALLINT UNSIGNED NOT NULL DEFAULT 8,
Permissions INT UNSIGNED NOT NULL DEFAULT 0,
Status SMALLINT UNSIGNED NOT NULL DEFAULT 0,
Timeout SMALLINT UNSIGNED NOT NULL DEFAULT 180);

CREATE TABLE users_info (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
Path TEXT NOT NULL, INDEX (Path(20)),
Folder TEXT NOT NULL, INDEX (Path(20)),
Info TEXT NOT NULL,
Password CHAR(64) NOT NULL UNIQUE,
Email TINYTEXT NOT NULL,
FirstName TINYTEXT NOT NULL,
LastName TINYTEXT NOT NULL,
Institution TINYTEXT NOT NULL,
Address TINYTEXT NOT NULL,
Country TINYTEXT NOT NULL,
ResearchDesc TEXT NOT NULL,
PwHint TINYTEXT NOT NULL,
WhereHeardOfSuite TEXT NOT NULL);

CREATE TABLE registrations_info (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
Path TEXT NOT NULL, INDEX (Path(20)),
Folder TEXT NOT NULL, INDEX (Path(20)),
Info TEXT NOT NULL,
Password CHAR(64) NOT NULL UNIQUE,
Email TINYTEXT NOT NULL,
FirstName TINYTEXT NOT NULL,
LastName TINYTEXT NOT NULL,
Institution TINYTEXT NOT NULL,
Address TINYTEXT NOT NULL,
Country TINYTEXT NOT NULL,
ResearchDesc TEXT NOT NULL,
PwHint TINYTEXT NOT NULL,
WhereHeardOfSuite TEXT NOT NULL,
Visibility TINYINT UNSIGNED DEFAULT 0);

CREATE TABLE bg_processes (
Session CHAR(20) NOT NULL, INDEX (Session),
Pid MEDIUMINT NOT NULL,
CurrentRun SMALLINT UNSIGNED NOT NULL,
TotalRuns SMALLINT UNSIGNED NOT NULL,
LastReadPosition INT UNSIGNED NOT NULL,
Username TINYTEXT NOT NULL,
Feature TINYTEXT NOT NULL,
Dir TEXT NOT NULL,
Command TEXT NOT NULL);


##### BBN SIMULATOR #####
CREATE TABLE bbn_sim_types_info (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
Path TEXT NOT NULL, INDEX (Path(20)),
Folder TEXT NOT NULL, INDEX (Path(20)),
Info TEXT NOT NULL,
SimType TINYTEXT NOT NULL,
TIME_STEP_CONSTANT1     DOUBLE PRECISION,
TIME_STEP_CONSTANT2     DOUBLE PRECISION,
INITIAL_TIMESTEP        DOUBLE PRECISION,
INITIAL_TEMPERATURE     DOUBLE PRECISION,
FINAL_TEMPERATURE       DOUBLE PRECISION,
SMALLEST_ABUND_ALLOWED  DOUBLE PRECISION,
ACCUMULATION_INCREMENT  DOUBLE PRECISION,
GRAVITATIONAL_CONSTANT  DOUBLE PRECISION,
NEUTRON_LIFETIME        DOUBLE PRECISION,
NUMBER_NEUTRINO_SPECIES DOUBLE PRECISION,
ETA                     DOUBLE PRECISION,
COSMOLOGICAL_CONSTANT   DOUBLE PRECISION,
XI_ELECTRON             DOUBLE PRECISION,
XI_MUON                 DOUBLE PRECISION,
XI_TAUON                DOUBLE PRECISION);

CREATE TABLE loop_def_data (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
DataID INT UNSIGNED NOT NULL AUTO_INCREMENT,
Label TINYTEXT NOT NULL,
SuggestedMin DOUBLE PRECISION,
SuggestedMax DOUBLE PRECISION,
IncrementLin DOUBLE PRECISION,
IncrementLog DOUBLE PRECISION,
LowerBound   DOUBLE PRECISION,
UpperBound   DOUBLE PRECISION,
PRIMARY KEY(DataID));

CREATE TABLE loop_def_links (
Path TEXT NOT NULL, INDEX (Path(20)),
DataID INT UNSIGNED NOT NULL);


##### BBN VISUALIZER #####
CREATE TABLE bbn_vis_info (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
Path TEXT NOT NULL, INDEX (Path(20)),
Folder TEXT NOT NULL, INDEX (Path(20)),
Info TEXT NOT NULL,
Recipe MEDIUMTEXT NOT NULL,
LibPath TEXT NOT NULL,
RateUncerPath TEXT NOT NULL,
MonteCarloList TEXT NOT NULL,
MonteCarloTrials INT UNSIGNED NOT NULL,
LoopingList TEXT NOT NULL,
Changes TEXT NOT NULL);

CREATE TABLE bbn_vis_data (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
DataID INT UNSIGNED NOT NULL AUTO_INCREMENT,
Constraints TEXT,
MonteCarloTrials INT UNSIGNED NOT NULL,
TIME_STEP_CONSTANT1     DOUBLE PRECISION,
TIME_STEP_CONSTANT2     DOUBLE PRECISION,
INITIAL_TIMESTEP        DOUBLE PRECISION,
INITIAL_TEMPERATURE     DOUBLE PRECISION,
FINAL_TEMPERATURE       DOUBLE PRECISION,
SMALLEST_ABUND_ALLOWED  DOUBLE PRECISION,
ACCUMULATION_INCREMENT  DOUBLE PRECISION,
GRAVITATIONAL_CONSTANT  DOUBLE PRECISION,
NEUTRON_LIFETIME        DOUBLE PRECISION,
NUMBER_NEUTRINO_SPECIES DOUBLE PRECISION,
ETA                     DOUBLE PRECISION,
COSMOLOGICAL_CONSTANT   DOUBLE PRECISION,
XI_ELECTRON             DOUBLE PRECISION,
XI_MUON                 DOUBLE PRECISION,
XI_TAUON                DOUBLE PRECISION,
Temp                    TEXT,
N_H                     TEXT,
P                       TEXT,
D_H                     TEXT,
T_H                     TEXT,
3He_H                   TEXT,
4He                     TEXT,
6Li_H                   TEXT,
7Li_H                   TEXT,
7Be_H                   TEXT,
8Li_H_up                TEXT,
T                       TEXT,
rhog                    TEXT,
rhoe                    TEXT,
rhone                   TEXT,
rhob                    TEXT,
phie                    TEXT,
dt                      TEXT,
eta_                    TEXT,
H                       TEXT,
_min                    TEXT,
_mid                    TEXT,
_max                    TEXT,
PRIMARY KEY(DataID));

CREATE TABLE bbn_vis_links (
Path TEXT NOT NULL, INDEX (Path(20)),
DataID INT UNSIGNED NOT NULL);


##### BBN OBSERVATIONS #####
CREATE TABLE bbn_obs_info (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
Path TEXT NOT NULL, INDEX (Path(20)),
Folder TEXT NOT NULL, INDEX (Path(20)),
Info TEXT NOT NULL,
Recipe MEDIUMTEXT NOT NULL);

CREATE TABLE bbn_obs_data (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
DataID INT UNSIGNED NOT NULL AUTO_INCREMENT,
Label TINYTEXT NOT NULL,
ObsMin DOUBLE PRECISION,
ObsMid DOUBLE PRECISION,
ObsMax DOUBLE PRECISION,
PRIMARY KEY(DataID));

CREATE TABLE bbn_obs_links (
Path TEXT NOT NULL, INDEX (Path(20)),
DataID INT UNSIGNED NOT NULL);


##### CONSTRAINT GENERATOR #####
CREATE TABLE constraint_info (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
Path TEXT NOT NULL, INDEX (Path(20)),
Folder TEXT NOT NULL, INDEX (Path(20)),
Info TEXT NOT NULL,
Recipe MEDIUMTEXT NOT NULL,
ObsPath TEXT NOT NULL,
BbnRunPath TEXT NOT NULL);

CREATE TABLE constraint_data (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
DataID INT UNSIGNED NOT NULL AUTO_INCREMENT,
Label TINYTEXT NOT NULL,
MinPoints TEXT,
MidPoints TEXT,
MaxPoints TEXT,
EtaRanges TEXT,
PRIMARY KEY(DataID));

CREATE TABLE constraint_links (
Path TEXT NOT NULL, INDEX (Path(20)),
DataID INT UNSIGNED NOT NULL);


##### RATE LIBRARY #####
CREATE TABLE rlib_info (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
Path TEXT NOT NULL, INDEX (Path(20)),
Folder TEXT NOT NULL, INDEX (Path(20)),
Info TEXT NOT NULL,
Recipe MEDIUMTEXT NOT NULL);

CREATE TABLE rlib_data (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
DataID INT UNSIGNED NOT NULL AUTO_INCREMENT,
ReactionID INT UNSIGNED NOT NULL,
ParmCount SMALLINT UNSIGNED NOT NULL,
Parameters TEXT NOT NULL,
Biblio TINYTEXT NOT NULL,
RNr TINYTEXT NOT NULL,
Info TEXT NOT NULL,
PRIMARY KEY(DataID));

CREATE TABLE rlib_links (
Path TEXT NOT NULL, INDEX (Path(20)),
DataID TINYTEXT NOT NULL);

CREATE TABLE reaction_lookup (
ReactionID INT UNSIGNED NOT NULL AUTO_INCREMENT,
ReaclibType TINYINT NOT NULL,
ReactantZ SMALLINT UNSIGNED NOT NULL,
ReactantA SMALLINT UNSIGNED NOT NULL,
ProductZ SMALLINT UNSIGNED NOT NULL,
ProductA SMALLINT UNSIGNED NOT NULL,
ReactionString TINYTEXT NOT NULL,
AllReactants TINYTEXT NOT NULL,
AllProducts TINYTEXT NOT NULL,
DecayType TINYTEXT,
PRIMARY KEY(ReactionID));

##### RATE UNCERTAINTY #####
CREATE TABLE rate_uncer_info (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
Path TEXT NOT NULL, INDEX (Path(20)),
Folder TEXT NOT NULL, INDEX (Path(20)),
Info TEXT NOT NULL,
Recipe MEDIUMTEXT NOT NULL);

CREATE TABLE rate_uncer_data (
CreateDate DATETIME NOT NULL,
ModDate DATETIME NOT NULL,
DataID INT UNSIGNED NOT NULL AUTO_INCREMENT,
ReactionID INT UNSIGNED NOT NULL,
Uncertainty DOUBLE PRECISION NOT NULL,
Info TEXT NOT NULL,
Props MEDIUMTEXT NOT NULL,
PRIMARY KEY(DataID));

CREATE TABLE rate_uncer_links (
Path TEXT NOT NULL, INDEX (Path(20)),
DataID TINYTEXT NOT NULL);






CONVENIENCE REQUESTS
INSERT INTO _info (CreateDate,ModDate,Path,Folder,Info,Recipe) VALUES (now(),now(),'/PUBLIC/test','/PUBLIC/','test','new info table');
INSERT INTO _data (CreateDate,ModDate,DataID,) VALUES (now(),now(),0,);
INSERT INTO _links (Path,DataID) VALUES ('','');

# Make links for everything in rate_uncer_data
insert into rate_uncer_links (Path,DataID) select '/PUBLIC/test',rate_uncer_data.DataID from rate_uncer_data ;



##### ADMINISTRATION #####
INSERT INTO accounts (Username,Alias,Password,Email,CreateDate,PwChangeDate,MaxLogins) VALUES ('','',SHA1(''),'',DATE(NOW()),ADDDATE(DATE(NOW()),INTERVAL 1 YEAR),8);
UPDATE accounts SET Password=SHA1('') WHERE Username='';

INSERT INTO constraint_data (CreateDate,ModDate,DataID,Label,MinPoints,MidPoints,MaxPoints,EtaRanges) VALUES (now(),now(),0,'h2',
"6.44329E-10,2.38000E-05\t6.34837E-10,2.38000E-05\t6.54150E-10,2.38000E-05",
"5.85171E-10,2.78000E-05\t5.76288E-10,2.78000E-05\t5.93673E-10,2.78000E-05",
"5.37320E-10,3.18000E-05\t5.29293E-10,3.18000E-05\t5.44997E-10,3.18000E-05",
"5.29293E-10,6.54150E-10");

INSERT INTO constraint_data (CreateDate,ModDate,DataID,Label,MinPoints,MidPoints,MaxPoints,EtaRanges) VALUES (now(),now(),0,'he3',
"7.85906E-10,9.00000E-06\t7.45109E-10,9.00000E-06\t8.28816E-10,9.00000E-06",
"5.54908E-10,1.10000E-05\t5.31107E-10,1.10000E-05\t5.81165E-10,1.10000E-05",
"4.26231E-10,1.30000E-05\t4.08729E-10,1.30000E-05\t4.43046E-10,1.30000E-05",
"4.08729E-10,8.28816E-10");

INSERT INTO constraint_data (CreateDate,ModDate,DataID,Label,MinPoints,MidPoints,MaxPoints,EtaRanges) VALUES (now(),now(),0,'he4',
"3.52382E-10,2.40000E-01\t3.57271E-10,2.40000E-01\t3.47878E-10,2.40000E-01",
"4.27068E-10,2.42000E-01\t4.32511E-10,2.42000E-01\t4.21591E-10,2.42000E-01",
"5.21527E-10,2.44000E-01\t5.28324E-10,2.44000E-01\t5.14702E-10,2.44000E-01",
"3.47878E-10,5.28324E-10");

INSERT INTO constraint_data (CreateDate,ModDate,DataID,Label,MinPoints,MidPoints,MaxPoints,EtaRanges) VALUES (now(),now(),0,'li7',
"2.30043E-10,1.21000E-10\t2.87754E-10,1.21000E-10\t2.13680E-10,1.21000E-10\t3.08505E-10,1.21000E-10\t2.44303E-10,1.21000E-10\t2.59806E-10,1.21000E-10",
"2.24612E-10,1.23000E-10\t2.98072E-10,1.23000E-10\t2.07849E-10,1.23000E-10\t3.12483E-10,1.23000E-10\t2.39222E-10,1.23000E-10\t2.68692E-10,1.23000E-10",
"1.62341E-10,1.91000E-10\t3.97046E-10,1.91000E-10\t1.54850E-10,1.91000E-10\t4.10699E-10,1.91000E-10\t1.68775E-10,1.91000E-10\t3.82909E-10,1.91000E-10",
"1.54850E-10,2.443034E-10\t2.598059E-10,4.106994E-10");

